name: CI

run-name: "${{ github.event_name == 'pull_request' && 'PR Quality Checks' || 'Continous Integration' }}"

on:
  push:
    branches: ['develop']
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
      - 'tsconfig.*'
      - 'vitest.config.ts'
      - '.nvmrc'
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
      - 'tsconfig.*'
      - 'vitest.config.ts'
      - '.nvmrc'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build
